### ISSUE TITLE
Uncaught TypeError: Cannot read property 'camelize' of null

### ISSUE THREAD

**Issue by oskarkrawczyk** [kamicane/moofx#15]
This has happened when upgrading 3.0.10 to 3.0.14.

Line 358: `string` vars are left undefined.

**Comment by arian** [comment]
I don't get this problem, how did you build moofx? Maybe if you've cloned the repo and used `distribute` you'll need to `npm update` first.

```
$ npm ls
/home/arian/www/test
└─┬ moofx@3.0.14
  ├── cubic-bezier@0.1.2
  ├─┬ elements@0.0.9
  │ └── slick@1.9.2
  └── prime@0.0.6
$ wrup -r moofx moofx -o moofx.js
```

**Comment by oskarkrawczyk** [comment]
``` bash
oskar@Serenity ~/Sites/moofx master ➔ npm ls
moofx@3.0.14 /Users/oskar/Sites/moofx
├── cubic-bezier@0.1.2
├─┬ elements@0.0.9
│ ├── prime@0.0.6
│ └── slick@1.9.2
└── prime@0.0.6
```

File build with `./distribute`.

By looking at the generated code, I'm not quite sure how is this supposed to work:

``` javascript
var prime = require("5"), array = require("3"), string = null;

var camelize = string.camelize, clean = string.clean, capitalize = string.capitalize;

[...]

var hyphenate = function(self) {
    return hyphenated[self] || (hyphenated[self] = string.hyphenate(self));
};
```

All the string methods are being executed on a `null`.

Maybe I'm missing something here.

**Comment by arian** [comment]
Ah, you should checkout the latest tag `v3.0.14`, and use `./makejs` with wrapup 0.9 (`npm install wrapup@0.9`, makejs uses the wrapup JS api, which has changed between 0.9 and 0.10).
The latest commit breaks the master branch, which uses the `winter-cleaning` branch of prime, don't really know why @kamicane updated the code already in master...

Alternatively you can just `npm install moofx` and `wrup -r moofx moofx -o moofx.js`.

**Comment by oskarkrawczyk** [comment]
I see. I'll wait until `master` is fully working again.

It's a good idea to stick to the good ol' "master is always deployable" rule :neckbeard:

**Comment by oskarkrawczyk** [comment]
Wanted to give the tag method a go anyway, but got this:

``` bash
➔ ./makejs 

              .- 3.0.14
  .-.-..-..-.-|-._.
  ' ' '`-'`-' ' ' '


/Users/oskar/Sites/moofx/makejs:28
    wrup.log("  ERROR: ")
         ^
TypeError: Object [object Object] has no method 'log'
    at wrupit (/Users/oskar/Sites/moofx/makejs:28:10)
    at Object.<anonymous> (/Users/oskar/Sites/moofx/makejs:46:1)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
```

``` bash
wrup --version
0.9.12
```

But I guess this is caused by something wrong on my end.

**Comment by arian** [comment]
Yeah, if you npm ls it's there is still wrapup@0.10 in your node_modules,
by doing `npm install wrapup@0.9` it will use the correct one. The makejs
uses the 'local' wrapup (in node_modules), not the global one (in /usr/bin).

**Comment by oskarkrawczyk** [comment]
Got it! Now it works. Thanks a lot Arian!

**Comment by kamicane** [comment]
Yeah I was using a branch to test, 8171bfba71d8aceb919464723a0f1c57e52d7b3f fixed it.
