### ISSUE TITLE
Generated file is indicating two different versions

### ISSUE THREAD

**Issue by oskarkrawczyk** [kamicane/moofx#16]
Cloned from the repo, and after generating a single file the versions state:

``` javascript
/*

---
provides: moofx
version: 3.0.14
```

And later in the code:

``` javascript
moofx.version = "3.0.11-dev";
```

Looking at the commit list, 3.0.14 is the correct one.

**Comment by kamicane** [comment]
Yeah I completely forgot to update the version in the code a while ago.
I'll probably just get rid of the version in the code come the next tag.
The only way to pick a version should be through tags on github, or through npm install. Master is always a work in progress.
