### ISSUE TITLE
Ability to transform translate3d, scale3d, rotate3d

### ISSUE THREAD

**Issue by oskarkrawczyk** [kamicane/moofx#17]
It would be great if we could transform these using moofx:
- `translate3d(tx, ty, tz)`
- `scale3d(sx, sy, sz)`
- `rotate3d(rx, ry, rz, angle)`

**Comment by kamicane** [comment]
It should already be possible.

```
$(x).animate("transform", "rotate3d(...)")
```

If it's not working, then there's some bug with the code.
Personally I have only used the rotateX/Y notation, but don't see why 3d should not work.

**Comment by oskarkrawczyk** [comment]
Ok, you're right it works. I tested it this morning, **before** coffee so I was definitely doing something wrong.
