### ISSUE TITLE
Integer duration option issue. Is README.md outdated?

### ISSUE THREAD

**Issue by lorenzos** [kamicane/moofx#2]
I was just playing with **moofx** when I noticed that the `duration` option do not work if an integer number (intended as milliseconds) is given.

```
moofx(el).animate('height', 300, { duration: 10000 }); // Sets to 300px immediately
moofx(el).animate('height', 300, { duration: '10s' }); // Works
```

In _README.md_ lots of examples shows an integer `duration` option to specify durations in ms.

**Comment by kamicane** [comment]
It was indeed a bug, this is fixed in 3.0.4
