### ISSUE TITLE
Chrome 26 (currently beta) breaks moofx

### ISSUE THREAD

**Issue by oskarkrawczyk** [kamicane/moofx#21]
```
Uncaught TypeError: Cannot call method 'splice' of null moofx.js:583
remove3 moofx.js:583
prime.resetCSS moofx.js:657
prime.setTransitionCSS moofx.js:619
CSSAnimation.bSetTransitionCSS moofx.js:593
iterator
```

Around line 583.

Not quite sure which version is this - generated file shows two versions:

![Screen Shot 2013-02-28 at 9 59 20 PM](https://f.cloud.github.com/assets/34213/207235/d65cece0-81e9-11e2-84b8-5d530a2a3ddb.png)

**Comment by eerne** [comment]
All moofx 3.1.1-dev (ab7266b403bd) tests pass on Chromium 27.0.1425.0 (184931).

**Comment by oskarkrawczyk** [comment]
Roger. 3.1.1 works fine. Thanks!
