### ISSUE TITLE
Firefox 3.6 - Exception... "Not enough arguments"

### ISSUE THREAD

**Issue by subhaze** [kamicane/moofx#6]
uncaught exception: [Exception... "Not enough arguments" nsresult: "0x80570001 (NS_ERROR_XPC_NOT_ENOUGH_ARGS)" location: "JS frame :: https://raw.github.com/kamicane/moofx/master/moofx.js :: anonymous :: line 185" data: no]

I've added null as the second param for this: `var cts = getComputedStyle(node, null);`

When I tested that the error was gone but the animations did not work.

http://jsfiddle.net/subhaze/vPPKw/

**Comment by kamicane** [comment]
Let's just assume that Firefox 3.6 is not supported, since we're at version 18 now.
