### ISSUE TITLE
Stop animation

### ISSUE THREAD

**Issue by couto** [kamicane/moofx#8]
I can't seem to find a way on how to properly interrupt an animation that is currently running.
Is there any way at all of doing this?

**Comment by kamicane** [comment]
The only way to stop an animation (right now?) is to style a property using .style(). That will stop the animation for that particular css property.

For instance, while animating width, height and opacity you could force-set the height property to some value (using .style()) and the height animation would stop and be set to that specified value.

To stop the value and retain its current status you could use style(property, compute(property))

**Comment by GCheung55** [comment]
fx.js provides start/stop methods. Based on how you suggest to stop animation with style + compute and JSAnimation and CSSAnimation objs both have a stop method, couldn't a stop method be added to browser.js?
